name: fumiya_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  firebase_core: ^2.1.1
  cloud_firestore: ^4.0.4
  firebase_auth: ^4.1.1
  firebase_dynamic_links: ^5.0.4
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.6
  package_info_plus: ^3.0.2
  firebase_storage: ^11.0.7
  image_picker: ^0.8.6
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/local_html/

  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/futura.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/noto_sans_jp.otf
